Data Pre-processing

In [48]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

#necessary libraries

Handling Null Values

In [49]:
#Reading the csv file to fetch the data

volunteer = pd.read_csv('https://raw.githubusercontent.com/labib15/Machine-Learning-Datasets/main/volunteer_opportunities.csv')
volunteer.head(3) #3-> shows the first 3 rows

,opportunity_id,content_id,vol_requests,event_time,title,hits,summary,is_priority,category_id,category_desc,...,end_date_date,status,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,4996,37004,50,0,Volunteers Needed For Rise Up & Stay Put! Home...,737,Building on successful events last summer and ...,NaN,NaN,NaN,...,July 30 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5008,37036,2,0,Web designer,22,Build a website for an Afghan business,NaN,1.0,Strengthening Communities,...,February 01 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5016,37143,20,0,Urban Adventures - Ice Skating at Lasker Rink,62,Please join us and the students from Mott Hall...,NaN,1.0,Strengthening Communities,...,January 29 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
#returning (rows,columns) available in the data
volunteer.shape

(665, 35)

In [51]:
#counting the number of null values in each column
volunteer.isnull().sum()

opportunity_id          0
content_id              0
vol_requests            0
event_time              0
title                   0
hits                    0
summary                 0
is_priority           603
category_id            48
category_desc          48
amsl                  665
amsl_unit             665
org_title               0
org_content_id          0
addresses_count         0
locality               70
region                  0
postalcode              6
primary_loc           665
display_url             0
recurrence_type         0
hours                   0
created_date            0
last_modified_date      0
start_date_date         0
end_date_date           0
status                  0
Latitude              665
Longitude             665
Community Board       665
Community Council     665
Census Tract          665
BIN                   665
BBL                   665
NTA                   665
dtype: int64

Removing a Column

In [52]:
#Removing a column
volunteer = volunteer.drop(['BIN','BBL','NTA'], axis = 1) #dropping 3 columns
#axis = 1 means column , axis = 0 means row 
volunteer.shape

(665, 32)

Removing a Row

In [53]:

#number of null rows
null_vals=volunteer[volunteer['category_desc'].isnull()]
print("Number of null values" , null_vals.shape)
#number of nonNull rows
nonNull_vals=volunteer[volunteer['category_desc'].notnull()]
print("Number of non-null values",nonNull_vals.shape
)

Number of null values (48, 32)
Number of non-null values (617, 32)

In [54]:
#Old shape 
print("Old shape before removing the rows",volunteer.shape)

volunteer = volunteer.dropna(axis=0 , subset= ['category_desc'])

print("New shape after removing the rows",volunteer.shape)

Old shape before removing the rows (665, 32)
New shape after removing the rows (617, 32)

Imputing values

In [55]:
sales=pd.read_csv('https://raw.githubusercontent.com/labib15/Machine-Learning-Datasets/refs/heads/main/sales.csv', index_col = ['month'])
sales

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221   NaN    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [56]:
#Putting a fixed value in NaN
imputed_sales = sales.fillna(50)
imputed_sales

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221  50.0    72
Apr      77  87.0    20
May     132  50.0    52
Jun     205  60.0    55

In [57]:
sales = pd.read_csv('https://raw.githubusercontent.com/labib15/Machine-Learning-Datasets/refs/heads/main/sales.csv', index_col = ['month'])
sales.head(10)

       eggs  salt  spam
month
Jan      47  12.0    17
Feb     110  50.0    31
Mar     221   NaN    72
Apr      77  87.0    20
May     132   NaN    52
Jun     205  60.0    55

In [58]:
sales[['salt']]

       salt
month
Jan    12.0
Feb    50.0
Mar     NaN
Apr    87.0
May     NaN
Jun    60.0

In [ ]:
#Using Simple Imputer

from sklearn.impute import SimpleImputer

#Finding the average values and placing it in the NaN
#making the engine for imputation
impute = SimpleImputer(missing_values= np.nan , strategy= 'mean')

# .fit() makes the imputer scan the data and figure out the mean
impute.fit(sales[['salt']])

#transform uses the value from .fit() and stores it in the sales['salt'] 
sales['salt'] = impute.transform(sales[['salt']])

#after transformation
sales[['salt']]

        salt
month
Jan    12.00
Feb    50.00
Mar    52.25
Apr    87.00
May    52.25
Jun    60.00